targets = main_prog.c rev_radix_sort.c half_and_half.c number_generator.c quick_sort.c radix_half_sorted.c selection_sort.c radix_sort.c
all: build

build: 
		gcc -o main $(targets)

clean: rm main